import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ClipboardCheck, ArrowRight } from "lucide-react";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/card";
import { Table, Thead, Tbody, Tr, Th, Td } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Skeleton, SkeletonRow } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/empty-state";
import { relativeTime, fmt } from "@/lib/utils";

export function ReviewQueuePage() {
  const { data: queue, isLoading } = useQuery({
    queryKey: ["review-queue"],
    queryFn: () => api.review.queue(),
    refetchInterval: 30_000,
  });

  return (
    <div className="space-y-5">
      <div>
        <h1>Content Desk</h1>
        <p className="text-sm text-text-tertiary mt-1">
          Articles generated by the pipeline that need human review before publishing.
          {queue && queue.length > 0 && (
            <span className="ml-1 text-primary font-medium">{queue.length} item{queue.length !== 1 ? "s" : ""} in queue.</span>
          )}
        </p>
      </div>

      <Card>
        {isLoading ? (
          <Table>
            <Thead><Tr><Th>Title</Th><Th>Site</Th><Th>Quality</Th><Th>Retries</Th><Th>Age</Th><Th /></Tr></Thead>
            <Tbody>{Array.from({ length: 4 }).map((_, i) => <SkeletonRow key={i} cols={6} />)}</Tbody>
          </Table>
        ) : !queue?.length ? (
          <EmptyState
            icon={<ClipboardCheck className="size-10" />}
            title="Review queue is empty"
            description="All articles have been reviewed. New items appear when content jobs reach in_review state."
          />
        ) : (
          <Table>
            <Thead>
              <Tr>
                <Th>Title</Th>
                <Th>Site</Th>
                <Th>Quality</Th>
                <Th>Critique</Th>
                <Th>Retries</Th>
                <Th>Age</Th>
                <Th />
              </Tr>
            </Thead>
            <Tbody>
              {queue.map((item) => {
                const score = item.qualityScores?.overall;
                const pass = item.qualityScores?.pass;
                return (
                  <Tr key={item.id}>
                    <Td className="text-text-primary font-medium max-w-xs truncate">
                      {item.title ?? <span className="text-text-disabled italic">untitled</span>}
                    </Td>
                    <Td className="text-text-tertiary text-xs mono">{item.siteSlug}</Td>
                    <Td>
                      {score != null ? (
                        <Badge variant={pass ? "success" : "warning"}>
                          {fmt(score * 100, 0)}%
                        </Badge>
                      ) : "—"}
                    </Td>
                    <Td className="text-xs text-text-tertiary max-w-[200px] truncate">
                      {item.critique ?? "—"}
                    </Td>
                    <Td>
                      {item.retryCount > 0 ? (
                        <Badge variant="warning">{item.retryCount}</Badge>
                      ) : "—"}
                    </Td>
                    <Td className="text-text-tertiary text-xs">{relativeTime(item.createdAt)}</Td>
                    <Td>
                      <Link
                        to={`/review/${item.id}`}
                        className="inline-flex items-center gap-1 text-xs text-primary hover:text-primary-hover transition-colors"
                      >
                        Review <ArrowRight className="size-3" />
                      </Link>
                    </Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        )}
      </Card>
    </div>
  );
}
